spring:
  application:
    name: demo
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
