spring:
  application:
    name: demo
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: your-super-secret-key-that-is-at-least-32-characters-long
  expiration: 86400000  # 24小时（毫秒）

